stages:
  - build
  - test
  - lint

variables:
  REZ_LOCAL_PACKAGES_PATH: "${CI_PROJECT_DIR}/install"
  USER: "meshroomBatcher"

# Stage BUILD - Build package
build:package:
  stage: build
  script:
    - /s/apps/lin/rez/rez build -vic
  tags:
    - rez
    - linux

# Stage TEST - launch python tests
test:pytest:
  stage: test
  needs:
    - build:package
  script:
    - /s/apps/lin/rez/rez build -i
    - /s/apps/lin/rez/rez test meshroomBatcher-develop pytest
  coverage: '/TOTAL.*\s+(\d+%)$/'   # Regex to parse coverage % from output
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - coverage.xml
    expire_in: 1 week
  tags:
    - rez
    - linux

# Stage LINT - Check code quality
lint:ruff:
  stage: lint
  needs:
    - build:package
  script:
    - /s/apps/lin/rez/rez build -i
    - /s/apps/lin/rez/rez test meshroomBatcher-develop ruff
  tags:
    - rez
    - linux
